import { NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabaseAdmin';
import { getApiHost, getPortalHost } from '@/lib/paynet';
import { randomUUID, randomBytes } from 'crypto';

function validatePaynetEnvVars(): { isValid: boolean; missing: string[] } {
  const missing: string[] = [];
  
  // Required for all modes
  const requiredVars = [
    'PAYNET_ENV',
    'PAYNET_USERNAME',
    'PAYNET_PASSWORD',
    'PAYNET_MERCHANT_CODE',
    'PAYNET_SALE_AREA_CODE',
    'PAYNET_CALLBACK_URL',
  ];

  // Check required vars
  for (const varName of requiredVars) {
    if (!process.env[varName]) {
      missing.push(varName);
    }
  }

  const paynetEnv = process.env.PAYNET_ENV;

  // If in live mode, check live-specific vars
  if (paynetEnv === 'live') {
    if (!process.env.PAYNET_API_HOST_LIVE) {
      missing.push('PAYNET_API_HOST_LIVE');
    }
    if (!process.env.PAYNET_PORTAL_HOST_LIVE) {
      missing.push('PAYNET_PORTAL_HOST_LIVE');
    }
    if (!process.env.PAYNET_NOTIFY_SECRET_KEY_LIVE) {
      missing.push('PAYNET_NOTIFY_SECRET_KEY_LIVE');
    }
  } else {
    // Test mode (default)
    if (!process.env.PAYNET_API_HOST_TEST) {
      missing.push('PAYNET_API_HOST_TEST');
    }
    if (!process.env.PAYNET_PORTAL_HOST_TEST) {
      missing.push('PAYNET_PORTAL_HOST_TEST');
    }
    if (!process.env.PAYNET_NOTIFY_SECRET_KEY_TEST) {
      missing.push('PAYNET_NOTIFY_SECRET_KEY_TEST');
    }
  }

  return {
    isValid: missing.length === 0,
    missing,
  };
}

export async function POST(req: Request) {
  // Version guard to confirm new code is deployed
  console.log('PAYNET_CREATE_HANDLER_VERSION', 'attempts-v2');

  try {
    // Validate environment variables first
    const validation = validatePaynetEnvVars();
    if (!validation.isValid) {
      console.error('Missing Paynet environment variables:', validation.missing.join(', '));
      return NextResponse.json(
        {
          error: 'PAYNET_CONFIG_MISSING',
          missing: validation.missing,
        },
        { status: 500 }
      );
    }

    // Parse and validate request body
    let body;
    try {
      body = await req.json();
    } catch (e) {
      return NextResponse.json(
        {
          error: 'BAD_REQUEST',
          details: 'Invalid JSON in request body',
        },
        { status: 400 }
      );
    }

    const { productId, amount, currency = 'MDL' } = body;

    // Body validation
    if (!productId || typeof productId !== 'string' || productId.trim() === '') {
      return NextResponse.json(
        {
          error: 'BAD_REQUEST',
          details: 'productId is required and must be a non-empty string',
        },
        { status: 400 }
      );
    }

    if (!amount || typeof amount !== 'number' || amount <= 0) {
      return NextResponse.json(
        {
          error: 'BAD_REQUEST',
          details: 'amount is required and must be a positive number',
        },
        { status: 400 }
      );
    }

    // Generate invoice ONCE (reuse for all attempts)
    // Generate invoice as small integer (10 digits max) matching Reg.json style
    const invoice = Math.floor(Date.now() / 1000);

    // Insert into Supabase ONCE before trying any Paynet attempts
    // id (UUID) will be auto-generated by Supabase
    const { data, error: insertError } = await supabaseAdmin
      .from('orders')
      .insert({
        product_id: productId,
        amount: amount,
        currency: currency,
        status: 'pending',
        invoice: String(invoice),
        access_token: randomBytes(24).toString('base64url'), // Generate access token for Paynet orders too
      })
      .select()
      .single();

    if (insertError) {
      console.error('SUPABASE INSERT ERROR', insertError);
      return NextResponse.json(
        {
          error: 'SUPABASE_INSERT_FAILED',
          details: insertError.message,
          code: insertError.code ?? null,
          hint: insertError.hint ?? null,
        },
        { status: 500 }
      );
    }

    const orderId = data.id; // Use the auto-generated UUID

    const apiHost = getApiHost();
    const portalHost = getPortalHost();
    const merchantCode = process.env.PAYNET_MERCHANT_CODE!;
    const saleAreaCode = process.env.PAYNET_SALE_AREA_CODE!;
    const callbackUrl = process.env.PAYNET_CALLBACK_URL!;

    // Authenticate with Paynet (include salearea in auth per Postman example)
    const authParams = new URLSearchParams({
      grant_type: 'password',
      username: process.env.PAYNET_USERNAME!,
      password: process.env.PAYNET_PASSWORD!,
      merchantcode: merchantCode,
      salearea: saleAreaCode,
    });

    const authResponse = await fetch(`${apiHost}/auth`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: authParams.toString(),
    });

    if (!authResponse.ok) {
      const authErrorText = await authResponse.text();
      console.error('PAYNET AUTH STATUS', authResponse.status);
      console.error('PAYNET AUTH BODY', authErrorText);
      return NextResponse.json(
        {
          error: 'PAYNET_API_ERROR',
          step: 'auth',
          status: authResponse.status,
          details: authErrorText,
        },
        { status: 502 }
      );
    }

    let authData;
    try {
      authData = await authResponse.json();
    } catch (e) {
      console.error('PAYNET AUTH PARSE ERROR', e);
      return NextResponse.json(
        {
          error: 'PAYNET_AUTH_FAILED',
          details: 'Failed to parse auth response',
        },
        { status: 502 }
      );
    }

    const accessToken = authData.access_token || authData.token;

    if (!accessToken) {
      console.error('No access token in auth response:', authData);
      return NextResponse.json(
        {
          error: 'PAYNET_AUTH_FAILED',
          details: 'No access_token in response',
        },
        { status: 502 }
      );
    }

    // Build base URL for callbacks
    const baseUrl = callbackUrl.replace('/api/paynet/callback', '');
    // Date formatter: ISO without milliseconds and without 'Z'
    const iso = (d: Date) => d.toISOString().replace(/\.\d{3}Z$/, '');

    // Define attempts: PHP SDK structure (NO Signature, SignVersion, MoneyType, WITH Lang) vs Reg.json structure (WITH them, NO Lang)
    // Also test JSON vs form-urlencoded
    const attempts = [
      // PHP SDK structure: NO Signature, SignVersion, MoneyType, WITH Lang, Payer=Customer object
      // JSON format
      { id: 'A', endpoint: 'Send', usePhpSdkStructure: true, useJson: true, amountValue: Math.round(amount * 100), includeSaleArea: false, description: 'PHP SDK structure (no Signature/SignVersion/MoneyType), JSON, minor units' },
      { id: 'B', endpoint: 'Send', usePhpSdkStructure: true, useJson: true, amountValue: Math.round(amount), includeSaleArea: false, description: 'PHP SDK structure (no Signature/SignVersion/MoneyType), JSON, major units' },
      
      // Reg.json structure: WITH Signature, SignVersion, MoneyType, NO Lang, Payer=null
      // JSON format
      { id: 'C', endpoint: 'Send', usePhpSdkStructure: false, useJson: true, amountValue: Math.round(amount * 100), includeSaleArea: false, description: 'Reg.json structure (with Signature/SignVersion/MoneyType), JSON, minor units' },
      { id: 'D', endpoint: 'Send', usePhpSdkStructure: false, useJson: true, amountValue: Math.round(amount), includeSaleArea: false, description: 'Reg.json structure (with Signature/SignVersion/MoneyType), JSON, major units' },

      // Reg.json structure WITH SaleAreaCode
      { id: 'E', endpoint: 'Send', usePhpSdkStructure: false, useJson: true, amountValue: Math.round(amount * 100), includeSaleArea: true, description: 'Reg.json structure, WITH SaleAreaCode, minor units' },
      { id: 'F', endpoint: 'Send', usePhpSdkStructure: false, useJson: true, amountValue: Math.round(amount), includeSaleArea: true, description: 'Reg.json structure, WITH SaleAreaCode, major units' },
    ];

    const attemptResults: Array<{ attempt: string; status: number; body: string }> = [];

    // Try each attempt in order, stop on first success
    for (const attempt of attempts) {
      console.log('PAYNET_ATTEMPT', attempt.id);

      // Build payload INSIDE the loop for each attempt
      // Reuse invoice as small numeric (already generated above)
      const invoiceNumber = invoice; // Small number, ~10 digits

      // Build product matching Reg.json structure exactly
      const chosenAmount = attempt.amountValue;
      const product = {
        GroupName: null,
        QualitiesConcat: null,
        LineNo: 1,
        GroupId: null,
        Code: 'relatia360',
        Barcode: 3601,
        Name: 'RELAȚIA 360 – De la conflict la conectare',
        Description: 'Acces online',
        UnitPrice: chosenAmount, // int
        UnitProduct: null,
        Quantity: 100, // int - in minor units (100 = 1.00) per Reg.json example where 200 = 2.00
        Amount: null,
        Dimensions: null,
        Qualities: null,
        TotalAmount: chosenAmount, // int - should be UnitPrice * (Quantity/100) per PHP SDK calculation
      };

      // Build payload - PHP SDK structure vs Reg.json structure
      const basePayload: any = {
        Invoice: invoiceNumber, // NUMBER (small integer, ~10 digits)
        MerchantCode: merchantCode, // STRING "982657"
        LinkUrlSuccess: `${baseUrl}/multumim?order=${orderId}`,
        LinkUrlCancel: `${baseUrl}/plata?cancel=1&order=${orderId}`,
        Customer: {
          Code: 'no-reply@liliadubita.md', // Email-like as in Reg.json
          Name: 'Customer',
          NameFirst: 'Customer',
          NameLast: 'Customer',
          email: 'no-reply@liliadubita.md',
          Country: 'Moldova',
          City: 'Chisinau',
          Address: 'Online',
          PhoneNumber: '79306530', // 8-digit numeric string
        },
        Currency: 498, // int 498 for MDL
        ExternalDate: iso(new Date()), // "YYYY-MM-DDTHH:mm:ss"
        ExpiryDate: iso(new Date(Date.now() + 2 * 60 * 60 * 1000)), // +2 hours
        Services: [
          {
            Name: 'RELAȚIA 360',
            Description: 'Curs practic de comunicare în relații',
            Amount: chosenAmount, // Uppercase Amount (matching Reg.json)
            Products: [product], // Uppercase Products (matching Reg.json)
          },
        ],
      };

      // PHP SDK structure: NO Signature, SignVersion, MoneyType, WITH Lang, Payer=Customer
      // Reg.json structure: WITH Signature, SignVersion, MoneyType, NO Lang, Payer=null
      const regPayload: any = {
        ...basePayload,
        ...(attempt.usePhpSdkStructure ? {
          // PHP SDK structure
          Payer: {
            Code: 'no-reply@liliadubita.md',
            Name: 'Customer',
            NameFirst: 'Customer',
            NameLast: 'Customer',
            email: 'no-reply@liliadubita.md',
            Country: 'Moldova',
            City: 'Chisinau',
            Address: 'Online',
            PhoneNumber: '79306530',
          },
          Lang: 'ro', // PHP SDK includes Lang
          // NO Signature, SignVersion, MoneyType
        } : {
          // Reg.json structure
          Signature: null,
          SignVersion: 'v01', // Reg.json uses v01
          Payer: null, // Reg.json has Payer: null
          MoneyType: null,
          // NO Lang
        }),
        // Include SaleAreaCode only if attempt.includeSaleArea is true
        ...(attempt.includeSaleArea && { SaleAreaCode: saleAreaCode }),
      };

      // CRITICAL LOGGING: Log the exact payload that will be sent
      console.log('PAYNET_ATTEMPT', attempt.id);
      console.log('PAYNET_PAYLOAD_SENT', JSON.stringify(regPayload));

      // Determine endpoint path
      const endpointPath = attempt.endpoint ? `/api/Payments/${attempt.endpoint}` : '/api/Payments';

      // Determine Content-Type and body format
      // Note: PHP SDK uses form-urlencoded, but Postman uses JSON. Testing JSON first.
      const contentType = attempt.useJson ? 'application/json' : 'application/x-www-form-urlencoded';
      const requestBody = attempt.useJson 
        ? JSON.stringify(regPayload)
        : JSON.stringify(regPayload); // For now, keep JSON. Form-urlencoded would need nested structure flattening.

      // Try this attempt - use the payload built INSIDE this loop
      const paymentResponse = await fetch(`${apiHost}${endpointPath}`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': contentType,
        },
        body: requestBody,
      });

      const paymentResponseText = await paymentResponse.text();
      console.log('PAYNET_PAYMENTS_STATUS', paymentResponse.status);
      console.log('PAYNET_PAYMENTS_BODY', paymentResponseText);

      // Record attempt result
      attemptResults.push({
        attempt: attempt.id,
        status: paymentResponse.status,
        body: paymentResponseText,
      });

      // If successful, stop and return
      if (paymentResponse.ok) {
        let paymentData;
        try {
          paymentData = JSON.parse(paymentResponseText);
        } catch (e) {
          console.error('PAYNET PAYMENTS PARSE ERROR', e);
          // Continue to next attempt if parse fails
          continue;
        }

        const paymentId = paymentData.PaymentID || paymentData.id || paymentData.ID;
        const signature = paymentData.Signature || paymentData.signature;

        if (!paymentId) {
          console.error('No PaymentID in response:', paymentData);
          // Continue to next attempt
          continue;
        }

        // Update order with paynet_payment_id and signature
        const updateData: any = {
          paynet_payment_id: Number(paymentId),
        };

        if (signature) {
          updateData.paynet_signature = signature;
        }

        const { error: updateError } = await supabaseAdmin
          .from('orders')
          .update(updateData)
          .eq('id', orderId);

        if (updateError) {
          console.error('Failed to update order with payment ID:', updateError);
          // Continue anyway, payment was created
        }

        // Return success with attempt info
        return NextResponse.json({
          ok: true,
          orderId: orderId, // Use camelCase for consistency
          invoice: String(invoice),
          payment_id: paymentId.toString(),
          signature: signature || null,
          attempt: attempt.id,
          redirect_base: 'https://test.paynet.md/acquiring/getecom',
        });
      }

      // If not successful, continue to next attempt
      console.log(`PAYNET_ATTEMPT ${attempt.id} failed, trying next...`);
    }

    // All attempts failed
    return NextResponse.json(
      {
        error: 'PAYNET_PAYMENTS_FAILED',
        attempts: attemptResults,
        note: 'All 4 attempts (A, B, C, D) failed. Check PAYNET_ATTEMPT logs in Vercel.',
      },
      { status: 502 }
    );
  } catch (e) {
    console.error('PAYNET CREATE FATAL', e);
    return NextResponse.json(
      {
        error: 'Internal server error',
        details: String((e as any)?.message ?? e),
      },
      { status: 500 }
    );
  }
}

